---
title: 'Week 7: Gender and the World View'
author: Annelies Quinton
date: '2023-10-31'
slug: []
categories: []
tags: []
---

## Class Notes:

-   Why are women typically more liberal than men?

    -   Different reproductive strategies, men have more of a taste of hierarchy, and have an evolved trait that makes men more likely to seek power and political careers

    -   boys and girls are socialized differently: competitive sports

    -   influence of siblings:

-   systematic differences in political behavior:

    -   men are far more likely to hold political office than women

    -   men are on average more conservative

-   only 26/197 world leaders are women

    -   only 6 countries with more than 50% women (but could be due to quotas)

-   sexual selection leads to different selected pressures that demonstrates how and why women and men behave differently

    -   males have a taste for power

-   sources of deferentially socialized political behavior across genders:

    -   Household: parents and siblings

    -   sports: socialization reinforcing biology

-   Trager and Barnhart (2023): how women shape the politics of war

    -   women are more likely to engage in democratic peaceship

    -   "increasing levels of women suffrage = reduction conflict"

    -   "increasing democratic features without women has no impact on conflict likelihood"

    -   place with higher levels of political empowerment for women, gender gap is larger
