---
title: 'Week 4: Hierarchies'
author: Annelies Quinton
date: '2023-10-05'
slug: []
categories: []
tags: []
---





## Introduction

This week's blog post considers the role of hierarchies and the idea of social dominance theory. Social dominance orientation (SDO) refers to the "general support for the domination of certain socially constructed groups over other socially constructed groups, regardless of the manner in which these groups are defined" (Sidanious, 61). These groups can greatly vary including different demographic characteristics and belief systems, such as political orientation. The usage of SDO in this blog is through a 16 question survey. The picture below displays the survey:

## add qualtrics photo

The main question that drives this blog post is to what degree can vote choice be as a function of SDO and other variables of interest? Essentially, this blog uses vote choice as an outcome variable, and evaluates different models, all including SDO, to most effectively analyze the relationship between outcome and selected predictor variables.

## Data

The data used in this blog is a condensed version of survey conducted and generated by [Data for Progress](%5Bhttps://wthh.dataforprogress.org/get-the-data) in 2018. The data includes 3,144 rows (individuals) and 15 columns. The variables are primarily categorical variables, measuring the individuals' position on different questions with political undertones. The data also includes demographic variables such as race, education, sex, and age. The variables used in this blog are included below:

| Variable Name | Variable Description                                                                                                                                            |
|-------------------|-----------------------------------------------------|
| `sdo5`        | Five-point social dominance orientation (SDO) scale: 1. Minimum SDO; ...; 5. Maximum SDO                                                                        |
| `female`      | Indicator for whether or not the respondent is female. Coded 1 if respondent is female, 0 otherwise.                                                            |
| `birthyr`     | Respondent's birth year                                                                                                                                         |
| `educ`        | Education: 1. Didn't graduate HS; 2. HS graduate; 3. Some college; 4. 2-year college; 5. 4-year college; 6. Postgraduate                                        |
| `race`        | Race: 1. White; 2. Black or African-American; 3. Hispanic or Latino; 4. Asian or Asian-American; 5. Native American; 6. Mixed Race; 7. Other; 8. Middle Eastern |
| `favor_trump` | Favorability of Donald Trump: 1. very unfavorable; ...; 4. very favorable                                                                                       |
| `favor_blm`   | Favorability of Black Lives Matter: 1. very unfavorable; ...; 4. very favorable                                                                                 |
| `favor_metoo` | Favorability of the Me Too movement: 1. very unfavorable; ...; 4. very favorable                                                                                |
| `pid3`        | Three-category party identification: 1. Democrat; 2. Independent; 3. Republican                                                                                 |
| `ideo5`       | Five-category political ideology: 1. Very liberal; ...; 5. Very conservative                                                                                    |
| `presvote16`  | Vote choice in the 2016 presidential election                                                                                                                   |

## Social Dominance Orientation

Before analyzing the effectiveness of the model, it is important to consider the results from the survey and understand the distribution of SDO in the data set.The density plot below shows the distribution of `SDO` within the data set. The blue line represents the mean and the median in red. We see that both of these lines are very close together, the median is slightly smaller than the mean. Therefore, the average SDO value on a 5 point scale is \~2. However, there appears to be a large spike right at 1 and then a smaller one at 3. This shows that the most common SDO score was 1 and then 3, with an average around 2.

<img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" />

## Social Dominance By Party

Next, the density plots below break down SDO scores by party.

First, looking at the Democrat plot, we see that the most common score rating was dominantly 1. 2 and 3 were next, and there were no 4 or 5s. This indicates a possible connection between lower SDO scores for Democrats.

Looking at the Independent chart, there is a similar trend to the Democrat Chart, but with a lower magnitude. 1,2,3, all have similar densities, 4 has a very small number of people, and 5 has no people.

Finally, looking at the Republican graph, there is a parabolic nature to the density plot, with a maximum value at 3. The density for 3 on this graph is the highest among the three graphs. Similar to the other graphs, there are very few people at 4 and non at 5. The difference between this graph and the other two is that scores 1 and 2 do not have the highest density on the graph.

These three graphs display a possible link between party affiliation and SDO score. As people get more conservative, their SDO score similarly increases.

<img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" />

## SDO and Party Affiliation

The chart below looks at the correlation between SDO score and political affiliation. To measure political affiliation, the variable `favor_trump` is used. This variable goes from 1-4 with 4 being associated with "very favorable". In the chart below, each circle represents a different coordinate of SDO and Trump favorability. The size of the circle corresponds to the proportion of individuals with that score for Trump, among individuals with a certain SDO score. For example, at point (1,1) on the graph, the circle represents the proportion of individuals who no favorability for Trump (1) among those that also have a SDO score of 1.

From the chart, we can see that at scores 1 and 4 for Trump, there is a significant trend among the circles. At score 4, the circles get larger as SDO increases and at score 1, the circles get smaller as SDO increases. This follows the trend noticed in the earlier graphs. As SDO increases, people become more conservative.

<img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" />

## Fitting a Model

After evaluating the relationship between SDO and party affiliation, I created a model with republican votes in the 2016 presidential election the outcome variable. In order to make the model, I first had to add two variables, `white` and `rep_votes`. `white` considers race as binary variable, with "white" being 1 and all other cases as 0. `rep_votes` is also a binary variable, with Trump as 1 and any other candidate 0.

I fit three models and display the results in the table below:


<table style="text-align:center"><caption><strong>Regression Results</strong></caption>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"></td><td colspan="4"><em>Dependent variable:</em></td></tr>
<tr><td></td><td colspan="4" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align:left"></td><td colspan="4">Republican Votes</td></tr>
<tr><td style="text-align:left"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">SDO [sdo5]</td><td>0.304<sup>***</sup></td><td>0.284<sup>***</sup></td><td>0.093<sup>***</sup></td><td>0.093<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.008)</td><td>(0.008)</td><td>(0.007)</td><td>(0.007)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Race [white]</td><td></td><td>0.177<sup>***</sup></td><td>0.043<sup>***</sup></td><td>0.043<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.019)</td><td>(0.015)</td><td>(0.015)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Gender [female]</td><td></td><td>-0.021</td><td>-0.002</td><td></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.015)</td><td>(0.011)</td><td></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Education [educ]</td><td></td><td>-0.039<sup>***</sup></td><td>-0.017<sup>***</sup></td><td>-0.017<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.006)</td><td>(0.004)</td><td>(0.004)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Age [age]</td><td></td><td>0.003<sup>***</sup></td><td>0.001<sup>***</sup></td><td>0.002<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.001)</td><td>(0.0004)</td><td>(0.0004)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Party ID [pid3]</td><td></td><td></td><td>0.264<sup>***</sup></td><td>0.264<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td>(0.010)</td><td>(0.010)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Ideology [ideo5]</td><td></td><td></td><td>0.111<sup>***</sup></td><td>0.110<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td>(0.007)</td><td>(0.007)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Constant</td><td>-0.183<sup>***</sup></td><td>-0.314<sup>***</sup></td><td>-0.646<sup>***</sup></td><td>-0.649<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.018)</td><td>(0.045)</td><td>(0.034)</td><td>(0.031)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">Observations</td><td>2,982</td><td>2,982</td><td>2,749</td><td>2,749</td></tr>
<tr><td style="text-align:left">R<sup>2</sup></td><td>0.320</td><td>0.362</td><td>0.681</td><td>0.681</td></tr>
<tr><td style="text-align:left">Adjusted R<sup>2</sup></td><td>0.320</td><td>0.361</td><td>0.680</td><td>0.680</td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"><em>Note:</em></td><td colspan="4" style="text-align:right"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>
</table>

#### Just SDO

In the first model, I just look at the predictive power of SDO on republican votes. Importantly, we see that the coefficient for SDO is significant at the 95% confidence interval. This means there is a .304 increase in Trump vote for additional unit increase in SDO. The adjusted R\^2 value is 0.320.

#### SDO and Demographics model

The second model considers SDO along with gender, race, education, and age. In this model, all variables are significant at the 95% confidence level except for race. The adjusted R\^2 value is 0.361. This is slightly higher than model 1.

#### SDO, Demographics, and Ideology Model

The third model considers all the variables (adding party and ideology). Like model 2, gender is the only variable that is not significantly significant. The adjusted R\^2 for this model is much higher than the other 2 models, 0.680.

#### SDO, Demographics (No Gender), and Ideology, Model

The fourth, and final model, removes race from the previous model. Now, all predictors are statistically significant and the adjusted R\^2 value is 0.680.

#### Comparison of Models

Among the four models, the fourth most accurately fits the data because it has the highest adjusted R\^2 value and all variables are statistically significant. Interestingly, Party ID and SDO have the largest coefficients. These means, that when holding all the other variables constant, these variables will have the biggest sway in the outcome variable of republican votes. This makes sense considering how significant party affiliation is for voters and that SDO is connected to political ideology (seen in the earlier sections).

### talk about gender

## Discussion

## References
