---
title: 'Week 8: Symbolic Politics'
author: Annelies Quinton
date: '2023-11-6'
slug: []
categories: []
tags: []
---

## Class Notes:

-   state can have monopoly on legitimate use of force

-   why do people riot/violence?

    -   critque on violence: Sears and McConahay 1973 "The riot is assigned about as much symbolic political meaning as a drunken brawl in a tavern"

    -   when evaluating a complex political object, people rely on symbolic predispositions that were socialized early in life

-   what are symbolic attitudes/positions:

    -   most stable attitudes (stability)

    -   consistent responses over similar attitude objects (constraint)

    -   most influential toward other objects (power)

-   Busing:

    -   attitudes on busing was entirely based on early attitudes

    -   regression shows intolerance has highest coefficient

-   Objects in American Politics that are associated with stable, consistent, and powerful:

    -   constitution

-   longitudinal study demonstrates that group attitudes are powerful and stable and can predict political orientation

-   Sam Huntington: Political Order in Changing Societies:

    -   Mau Mau Uprising (1952-1960), claimed education in the colonies contributed to rioting

-   symbolic and modern racism is based on the racial resentment scale

    -   how can it measure both? attitudes that are socially early and stable and looks at race through both modern (1950s) and old perspectives

-   racial resentment scales:

    -   critique is measures conservatism not racism
